In [1]:
import numpy as np

***NumPy is a Python library used for working with arrays.NumPy stands for Numerical Python.n Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.***

In [2]:
my_arr = np.array([3,34,4,24,65])  #This a simple one dimensional array numpy array

In [3]:
my_arr[3]

24

In [4]:
my_arrr = np.array(([[56,5,6,3,5,4]]),np.int32)  # This  is a two dimesional array and int32,int8,int64 are the datatype which convertes the array in integer datatype

In [5]:
my_arrr

array([[56,  5,  6,  3,  5,  4]])

In [6]:
my_arrr[0,5]   #[ROW,COLUMN]

4

In [7]:
my_arrr.shape  #shape gives number of rows and column

(1, 6)

In [8]:
my_arrr.dtype  # dtype provides datatype of an array

dtype('int32')

In [9]:
my_arrr[0,2] = 9 # change value at index 0,2 row=0, column=2

In [10]:
my_arrr

array([[56,  5,  9,  3,  5,  4]])

***There are 6 general mechanisms for creating arrays:***

1. Conversion from other Python structures (i.e. lists and tuples)

2.  Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3.  Replicating, joining, or mutating existing arrays

4.  Reading arrays from disk, either from standard or custom formats

5.  Creating arrays from raw bytes through the use of strings or buffers

6.  Use of special library functions (e.g., random)


## *Conversion from other Python structures (i.e. lists and tuples)*

In [14]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])  # converting a list into numpyarray

In [15]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
listarray[1,1] = 14

In [21]:
listarray

array([[ 1,  2,  3],
       [ 5, 14,  5],
       [ 0,  3,  1]])

In [23]:
np.array({34,36,64})   # always take integer or float value for efficient calculation

array({64, 34, 36}, dtype=object)

## *Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)*

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.shape

(2, 5)

In [27]:
zeros.dtype

dtype('float64')

In [28]:
rng = np.arange(16)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
lspace = np.linspace(1,5,10)  #syntax: (first_number,last_number,number_of element in nupyarray)

In [40]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
emp = np.empty((4,6))  # Empty dunction creates a array with random values

In [35]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811083e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 8.06638080e-308, 8.01106038e-307,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

In [41]:
emp_like = np.empty_like(lspace)  # emp_like function take one array and copy that array and fill it with random values 

In [42]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
ide = np.identity(45) # it will give a identity matrix and size provided in parathenses

In [44]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [45]:
ide.shape  #shape is 45 rows and 45 column 

(45, 45)

In [46]:
arr = np.arange(99)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
 arr = arr.reshape(3,33)

In [53]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [58]:
arr = arr.ravel()    # It provides a one dimensional  numpy array

In [61]:
arr.shape  #it provides one dimesional array

(99,)

In [62]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [63]:
ar = np.array(x)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
ar.sum(axis=0)  # sum of column values

array([12,  8,  9])

In [66]:
ar.sum(axis=1) # sum of rows values

array([ 6, 15,  8])

In [68]:
ar.T   #transpose rows becomes column and vice versa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
ar.flat

In [71]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [72]:
ar.ndim  #number of dimension

2

In [73]:
ar.size # number of element

9

In [74]:
ar.nbytes

36

In [75]:
one = np.array([1,5,3,9,6,3])  #one dimensional array

In [76]:
one.argmax()  #index of maximum number

3

In [77]:
one.argmin()   #index of minimum number

0

In [78]:
one.argsort()  #sorted array

array([0, 2, 5, 1, 4, 3], dtype=int64)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar.argmax()

6

In [81]:
ar.argmin()

8

In [82]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [83]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [84]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [85]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [86]:
ar.ravel()  

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [88]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar2 = np.array([[1,2,1],
               [4,0,6],
               [8,1,0]])

In [91]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [92]:
[45,64,45] + [46,35,24]

[45, 64, 45, 46, 35, 24]

In [93]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [94]:
ar *2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [95]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [96]:
ar.max()


7

In [97]:
ar.min()

0

In [98]:
np.where(ar>5)  #index of element where ar is greter than 5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [99]:
type(np.where(ar>5)) # coverte array into tuple

tuple

In [100]:
np.count_nonzero(ar)

8

In [101]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [102]:
import sys

In [103]:
py_ar = [0,4,55,2]

In [104]:
np_ar = np.array(py_ar)

In [105]:
sys.getsizeof(1) * len(py_ar)

112

In [106]:
np_ar.itemsize * np_ar.size

16